### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by q8195438** [FleyX/teach_system#1]
loginSystem/node_modules/mysql/lib/protocol/Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^

**Comment by FleyX** [comment]
之前部署方式太麻烦，近期我会使用docker进行部署，到时可一键部署。（ps：这个错误信息提少，我也无能为力）

**Comment by FleyX** [comment]
@q8195438 docker部署已经实现
